import ReduxProvider from "../ComponentLibrary/wrapper/ReduxProvider";
import React from "react";
import "./globals.css";
export const metadata = {
  title: "E-Commerce App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
