import ReduxProvider from '../coreComponents/wrapper/ReduxProvider'
import React from "react";

export const metadata = {
  title: "E-Commerce App",
  description: "Generated by Next.js",
};

export default function RootLayout({children}:{children:React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider> 
      </body>
    </html>
  );
}
